fix format

diff --git a/.github/workflows/WhenPR.yml b/.github/workflows/WhenPR.yml
--- a/.github/workflows/WhenPR.yml
+++ b/.github/workflows/WhenPR.yml
@@ -1,80 +1,80 @@
-name: Run  Unit & Component Tests on iOS
+name: Run Unit & Component Tests on iOS
 
 run-name: ${{ github.actor }} is testing PR ${{ github.ref }} new code 🚀
+
 on:
   pull_request:
-    types: [opened,reopened,edited,synchronize]
+    types: [opened, reopened, edited, synchronize]
     branches:
       - main
       - release/release*
     paths:
       - '**'
   workflow_dispatch:
-  
+
 jobs:
-    Run-tests-on:
-      name: Run npm test
-      runs-on: macos-latest
-      permissions:
-        contents: write
-        pull-requests: write
-        
-      steps:
-        - name: Checkout repository
-          uses: actions/checkout@v4
-          with:
-            lfs: true
-        - name: Install the Apple certificate and provisioning profile
-          env:
-              BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
-              P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
-              BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
-              KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
-          run: |
-              # create variables
-              CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
-              PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
-              KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
-  
-              # import certificate and provisioning profile from secrets
-              echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
-              echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
-  
-              # create temporary keychain
-              security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-              security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
-              security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-  
-              # import certificate to keychain
-              security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
-              security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
-              security list-keychain -d user -s $KEYCHAIN_PATH
-  
-              # apply provisioning profile
-              mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
-              cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
-  
-        - name: Test 
-          run: 
-            |
-              set -eo pipefail # Ensure that failures in xcodebuild are captured
-              xcodebuild test \
-                -scheme EsmorgaiOS \
-                -sdk iphonesimulator \
-                -destination 'platform=iOS Simulator,name=iPhone 15,OS=' \
-                ONLY_ACTIVE_ARCH=YES \
-                -resultBundlePath TestResults.xcresult
+  Run-tests-on:
+    name: Run npm test
+    runs-on: macos-latest
+    permissions:
+      contents: write
+      pull-requests: write
 
-         - name: Upload xcresult if tests fail
-           if: failure()
-           uses: actions/upload-artifact@v3
-           with:
-             name: TestResults.xcresult
-             path: TestResults.xcresult
-             
-        - name: Clean up keychain and provisioning profile
-          if: ${{ always() }}
-          run: |
-                  security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
-                  rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          lfs: true
 
+      - name: Install the Apple certificate and provisioning profile
+        env:
+          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
+          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
+          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
+          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+        run: |
+          # create variables
+          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
+          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
+          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+
+          # import certificate and provisioning profile from secrets
+          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
+          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
+
+          # create temporary keychain
+          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+
+          # import certificate to keychain
+          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+          security list-keychain -d user -s $KEYCHAIN_PATH
+
+          # apply provisioning profile
+          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
+
+      - name: Run Tests
+        run: |
+          set -eo pipefail # Ensure that failures in xcodebuild are captured
+          xcodebuild test \
+            -scheme EsmorgaiOS \
+            -sdk iphonesimulator \
+            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.0' \
+            ONLY_ACTIVE_ARCH=YES \
+            -resultBundlePath TestResults.xcresult
+
+      - name: Upload xcresult if tests fail
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: TestResults.xcresult
+          path: TestResults.xcresult
+
+      - name: Clean up keychain and provisioning profile
+        if: ${{ always() }}
+        run: |
+          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
+          rm ~/Library/MobileDevice/Provisioning\ Profiles/build_pp.mobileprovision
