publish test results

diff --git a/.github/workflows/WhenPR.yml b/.github/workflows/WhenPR.yml
--- a/.github/workflows/WhenPR.yml
+++ b/.github/workflows/WhenPR.yml
@@ -57,7 +57,21 @@ jobs:
         - name: Test 
           run: 
             |
-              xcodebuild test  -scheme EsmorgaiOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' ONLY_ACTIVE_ARCH=YES
+              set -eo pipefail # Ensure that failures in xcodebuild are captured
+              xcodebuild test \
+                -scheme EsmorgaiOS \
+                -sdk iphonesimulator \
+                -destination 'platform=iOS Simulator,name=iPhone 15,OS=' \
+                ONLY_ACTIVE_ARCH=YES \
+                -resultBundlePath TestResults.xcresult
+
+         - name: Upload xcresult if tests fail
+           if: failure()
+           uses: actions/upload-artifact@v3
+           with:
+             name: TestResults.xcresult
+             path: TestResults.xcresult
+             
         - name: Clean up keychain and provisioning profile
           if: ${{ always() }}
           run: |
